### ISSUE TITLE
[Heroku] Error page 500 after logging in

### ISSUE THREAD

**Issue by burhanloey** [burhanloey/rumahsewa141#1]
Everything works fine in local but not in Heroku. It will display error page 500 after log in for both admin and normal user. Some important notes:
* The site does redirect normal user from admin routes and vice versa after log in, which means it starts having problem when trying to render the resources
* Heroku uses different version of Leiningen

**Comment by ShaneWilton** [comment]
❤️ 💚 💙 💛 💜

**Comment by burhanloey** [comment]
Apparently I accidentally added an extra '/' at the beginning of file path. Somehow the error did not show up in my system, only in Heroku.
